### ISSUE TITLE
[spike][React] Download a blob file

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/manfred-export-app#2]
Generate a simple we that will generate a hello world file with docx and we will show a button (no need to be styled) that will download the file

**Comment by SergioGordillo** [comment]
The task consists in:

· Generate a "Hello World" in docx format, using this library (https://github.com/dolanmiu/docx).
· Download it using a button on the PC of the user.

IMPORTANT: The "Hello World" is generated directly in docx format, not needed to do a conversion from JSON to docx in this story.

**Comment by SergioGordillo** [comment]
Task done here (https://github.com/SergioGordillo/LemoncodeMasterFrontend/tree/main/TFM).
