### ISSUE TITLE
Create text area and button in ManfredJson

### ISSUE THREAD

**Issue by manudous** [Lemoncode/manfred-export-app#25]
Create a textarea, a button in ManfredJson and when we click on the button do two things:

- If there is no content in the textarea, display an alert saying:

```js
alert('No content');
```

- If there is content in the textarea, display an alert saying:

```js
alert('here will go the export to word');
```

**Comment by abhinit2050** [comment]
Is this the file where you want your changes?

"https://github.com/Lemoncode/manfred-export-app/tree/main/apps/react-app/src/pods/manfred-json-input"

**Comment by abhinit2050** [comment]
Hi! I have done the necessary changes as mentioned in the issue but my pull request is denied as it requires at least one review. Can we do without it? As I searched, I learned that I have to create a branch and push my code in it. These are like 2 line changes, can you allow my pull request?

**Comment by brauliodiez** [comment]
Hello @abhinit2050 sorry there was another developer assigned to the case, if you are keen to participate on the project give me a buzz and I can assign you a case
