### ISSUE TITLE
[spike][Angular] Download a blob file

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/manfred-export-app#3]
Generate a simple we that will generate a hello world file with docx and we will show a button (no need to be styled) that will download the file

**Comment by jormazlop** [comment]
I have opted to try with the ngx-filesaver library -> https://www.npmjs.com/package/ngx-filesaver

In the documentation of the docx library, which will be used to generate the cv (at least, for the moment), is attached an example using angular and the file-saver library (https://stackblitz.com/edit/angular-wmd6k3?file=src%2Fapp%2Fapp.component.ts), so the idea is to generate a word document with the docx library (whose content is 'Hello World') and download the result in blob format with the ngx-filesaver library,  similar to the attached example.

**Comment by jormazlop** [comment]
Tested with ngx-filesaver version 14 in angular 15, working fine in chrome, firefox and edge -> https://github.com/jormazlop/TFM-Manfred/tree/master/blobFileAngularApp
