### ISSUE TITLE
[spike][Svelte] Download a blob file

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/manfred-export-app#4]
Generate a simple we that will generate a hello world file with docx and we will show a button (no need to be styled) that will download the file

**Comment by JavierOrtunoRoig** [comment]
He estado buscando alguna librería de Svelte para poder descargar archivos, pero no he encontrado nada útil, así que he decidido hacerlo con javascript vanilla.

[https://github.com/JavierOrtunoRoig/svelte-download-file](https://github.com/Lemoncode/manfred2word/issues/url)

**Comment by JavierOrtunoRoig** [comment]
@brauliodiez, ¿podrías echarle un ojo para ver si es esto lo que queremos? Intentaré mirar de nuevo a ver si encuentro alguna librería útil para hacerlo.
