### ISSUE TITLE
StylizeManfredJsonInput

### ISSUE THREAD

**Issue by SergioGordillo** [Lemoncode/manfred-export-app#46]
Add styles according to Figma to ManfredJsonInput

**Comment by brauliodiez** [comment]
Mocks

![image](https://user-images.githubusercontent.com/1457912/231422421-d39d7aed-f488-4b35-b768-ee600fbc2109.png)

![image (1)](https://user-images.githubusercontent.com/1457912/231422458-18a25474-cc36-40a7-936a-b46713d84d54.png)
