### ISSUE TITLE
[spike][Angular] Display JSON formatted text area

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/manfred-export-app#6]
Use code-mirror and bind it with Angular lifecycle

**Comment by hugomenz** [comment]
Added the steps to configure Angular to display a JSON formatted text area using codemirror in the wiki in the section `jsonrichformat/JSON Rich Format Text Area/Angular`

**Comment by hugomenz** [comment]
Link to repository https://github.com/hugomenz/spike_codemirror-Angular_integration
