### ISSUE TITLE
[spike][Svelte] Display JSON formatted text area

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/manfred-export-app#7]
Use code-mirror and bind it with Svelte lifecycle

**Comment by hugomenz** [comment]
Added the steps to configure Svelte to display a JSON formatted text area using codemirror in the wiki in the section `jsonrichformat / JSON Rich Format Text Area / Svelte`

**Comment by hugomenz** [comment]
Link to repository: https://github.com/hugomenz/spike_codemirror-Svelte_integration
