### ISSUE TITLE
[spike] how to create a library project with Vite

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/manfred-export-app#8]
I think it could be interesing to study

**Comment by brauliodiez** [comment]
https://onderonur.netlify.app/blog/creating-a-typescript-library-with-vite/

https://onderonur.netlify.app/blog/creating-a-typescript-library-with-vite/

**Comment by JavierOrtunoRoig** [comment]
He estado buscando alguna librería de Svelte para poder descargar archivos, pero no he encontrado nada útil, así que he decidido hacerlo con javascript vanilla.

[https://github.com/JavierOrtunoRoig/svelte-download-file](url)

**Comment by JavierOrtunoRoig** [comment]
@brauliodiez, ¿podrías echarle un ojo para ver si es esto lo que queremos? Intentaré mirar de nuevo a ver si encuentro alguna librería útil para hacerlo.

**Comment by Nasdan** [comment]
Implementation done
